# Generated by Django 5.1.2 on 2024-10-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
                ('city_population', models.FloatField(default=0)),
                ('city_province', models.CharField(max_length=200)),
                ('city_area', models.FloatField(default=0)),
            ],
        ),
    ]
