# Generated by Django 5.1.2 on 2024-10-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_population',
            field=models.IntegerField(default=0),
        ),
    ]
